version: '2'
services:
  nginx:
    env_file:
      - ./variables.env
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
  web-client:
    command: yarn start
    ports: 
      - '${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}'
  web-api:
    command: sbt run
    #volumes:
      #- ../services/web-api/sbt-root/plugins.sbt:/root/.sbt/0.13/plugins/plugins.sbt
      #- ../services/web-api/sbt-root/build.sbt:/root/.sbt/0.13/plugins/build.sbt
    ports: 
      - '${WEB_API_PORT}:${WEB_API_PORT}'
  postgres:
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

